name: Build Project
on: [push]

jobs: 
  installation: 
    runs-on: ubuntu-latest
    steps: 
      - name: Show event name
        run: echo "${{ github.event_name }} event is automatically triggering this job."

      - name: Show repository info
        run: echo "Repository is ${{ github.repository }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm install

  build: 
    runs-on: ubuntu-latest
    needs: installation
    steps: 
      - name: Show event name
        run: echo "${{ github.event_name }} event is automatically triggering this job."
